# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
<<<<<<< HEAD
# You can use `rake secret` to generate a secure secret key.
=======
# You can use `rails secret` to generate a secure secret key.
>>>>>>> ac88b1ce3a024e80a257d71624d22e1b8e57a03d

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

<<<<<<< HEAD
development:
  secret_key_base: 1db1e27666ed2beb4ff378f8e586bcd83e0c1bd98e0565e66a7b892b72a724f9a3fc3af808063513ce3f4ffe0484c758ae01171cad93d24b124564a34a0b2635

test:
  secret_key_base: 001604e89fd4a81d052557c63e7af9b01a8723cdd78fbf284d5e8e3ff7fbf6dd670d7eb581308c88a953e83627990fb55a1788e07bb01ba4f5dae32f00c7640a

# Do not keep production secrets in the repository,
# instead read values from the environment.
=======
# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 037b6242c8f1e3d4f571d55f8138dc0b9c46366f7cac35c1e7f60eee301350a17da3e9cbb7566f66d981eff6b976e6b5824f1c53332953509abb6d1e7cde10b8

test:
  secret_key_base: b7449c9ecaceb6c7ff81a65c2c0c224f6d2280482bee73f0b165fd7b99fc5707db4b2c28920e0a303ab1f6411d0d24a57d53103d813ad31b82f06587dccc68b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

>>>>>>> ac88b1ce3a024e80a257d71624d22e1b8e57a03d
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
